apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0009
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /var/lib/nfsshare/pv0009
    server: fedora.int.compunique.com
  persistentVolumeReclaimPolicy: Recycle